resourceserver:
  serviceName: resourceserver
  port: 8080
  disableTLS: true
  disableTelemetry: true
  region: dev
  numAccounts: 20
  usage:
    enabled: true
    delayReportSec: 5
    #type: http
    #url: http://localhost:8090/usage/set
    type: kafka
    url: localhost:9092
    options:
      topic: resourcecount

usageserver:
  serviceName: usageserver
  port: 8090
  disableTLS: true
  disableTelemetry: true
  usageDB: "postgres://postgres:postgres@localhost:15432/usage?sslmode=disable"
  msgSubscription:
    type: kafka
    url: localhost:9092
    options:
      topic: resourcecount
      consumer-group: resourcecount-consumers
#    type: amqp
#    url: amqp://localhost:5672
#    user: ratelimiter
#    password: pass
#    vhost: ratelimiter
#    exchangename: resourcecount
#    queue: usagedata
#    queueManager:
#      enabled: true
#      url: http://localhost:15672
#      user: ratelimiter
#      password: pass
#      queuePrefix: usagedata
#      maxQueuesNum: 10
  leaderElection:
    enabled: false
    url: localhost:6379
    relinquishInterval: 30
    leaderCheckInterval: 10
    followerCheckInterval: 10
  peerDiscovery:
    enabled: false
    gossipBindAddr: 127.0.0.1
    gossipPort: 18090
    seedPeers:
     - url: "127.0.0.1:18090"
     - url: "127.0.0.1:18091"
