resourceserver:
  serviceName: resourceserver
  port: 8080
  disableTLS: true
  disableTelemetry: true
  region: dev
  numAccounts: 20
  usage:
    enabled: true
    #type: http
    #url: http://localhost:8090/usage/set
    type: amqp
    url: amqp://localhost:5672
    options:
      vhost: ratelimiter
      exchangename: resourcecount
      user: ratelimiter
      password: pass
    delayReportSec: 5

usageserver:
  serviceName: usageserver
  port: 8090
  disableTLS: true
  disableTelemetry: true
  usageDB: "postgres://postgres:postgres@localhost:15432/usage?sslmode=disable"
  msgSubscription:
    url: amqp://localhost:5672
    user: ratelimiter
    password: pass
    vhost: ratelimiter
    exchangename: resourcecount
    queue: usagedata
    queueManager:
      enabled: true
      url: http://localhost:15672
      user: ratelimiter
      password: pass
      queuePrefix: usagedata
      maxQueuesNum: 10
  leaderElection:
    url: localhost:6379
    relinquishInterval: 30
    leaderCheckInterval: 10
    followerCheckInterval: 10
  peerDiscovery:
    gossipBindAddr: 127.0.0.1
    gossipPort: 18090
    seedPeers:
     - url: "127.0.0.1:18090"
     - url: "127.0.0.1:18091"
