resourceserver:
  serviceName: resourceserver
  port: 8080
  disableTLS: true
  disableTelemetry: true
  usage:
    enabled: true
    type: http
    url: http://localhost:8090/usage/set

usageserver:
  serviceName: usageserver
  port: 8090
  disableTLS: true
  disableTelemetry: true
